@extends('layouts.app')
@section('title', 'Payroll · '.$payroll->period_label)
@section('content')
<x-page-header :title="'Salary · '.$payroll->period_label" :subtitle="$payroll->employee->full_name.' · '.$payroll->employee->employee_code" :breadcrumbs="['Payroll' => route('payroll.index'), $payroll->period_label => null]">
    <x-slot:actions>
        <a href="{{ route('payroll.slip', $payroll) }}" target="_blank" rel="noopener" class="btn btn-light"><i class="bi bi-printer"></i> View / print slip</a>
        <a href="{{ route('payroll.slip', [$payroll, 'download' => 1]) }}" class="btn btn-light"><i class="bi bi-file-earmark-pdf"></i> Download PDF</a>
        @can('update', $payroll)<a href="{{ route('payroll.edit', $payroll) }}" class="btn btn-light"><i class="bi bi-pencil"></i> Edit</a>@endcan
        @can('approve', $payroll)
            <form method="POST" action="{{ route('payroll.approve', $payroll) }}">@csrf<button class="btn btn-primary"><i class="bi bi-check2-circle"></i> Approve</button></form>
        @endcan
        @can('markPaid', $payroll)
            <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#pay-modal"><i class="bi bi-wallet2"></i> Mark as paid</button>
        @endcan
        @can('delete', $payroll)<x-delete-button :action="route('payroll.destroy', $payroll)" title="Delete this payroll record?" label="Delete" size="" />@endcan
    </x-slot:actions>
</x-page-header>

<div class="row g-4">
    <div class="col-xl-8">
        <x-card>
            <div class="d-flex flex-wrap justify-content-between gap-3 mb-4">
                <x-person :employee="$payroll->employee" size="48" :sub="($payroll->employee->designation?->name ?? '—').' · '.($payroll->employee->department?->name ?? '—')" />
                <div class="text-end"><x-status-badge :status="$payroll->status" /><div class="small text-muted mt-1">{{ $payroll->paid_at ? 'Paid '.$payroll->paid_at->format('M d, Y').' via '.label($payroll->payment_method) : 'Not paid yet' }}</div></div>
            </div>
            <div class="row g-4">
                <div class="col-md-6">
                    <div class="small-caps mb-2 text-success">Earnings</div>
                    @foreach (['Basic salary' => $payroll->basic_salary, 'Allowances' => $payroll->allowances, 'Overtime' => $payroll->overtime, 'Bonus' => $payroll->bonus] as $l => $v)
                        <div class="d-flex justify-content-between py-2 border-bottom"><span class="text-muted">{{ $l }}</span><span>{{ money($v) }}</span></div>
                    @endforeach
                    <div class="d-flex justify-content-between py-2 fw-bold"><span>Gross salary</span><span>{{ money($payroll->gross_salary) }}</span></div>
                </div>
                <div class="col-md-6">
                    <div class="small-caps mb-2 text-danger">Deductions</div>
                    @foreach (['Deductions' => $payroll->deductions, 'Tax' => $payroll->tax, 'Other deductions' => $payroll->other_deductions] as $l => $v)
                        <div class="d-flex justify-content-between py-2 border-bottom"><span class="text-muted">{{ $l }}</span><span>{{ money($v) }}</span></div>
                    @endforeach
                    <div class="d-flex justify-content-between py-2 fw-bold"><span>Total deductions</span><span>{{ money($payroll->total_deductions) }}</span></div>
                </div>
            </div>
            <div class="op-hero mt-4 py-3 d-flex justify-content-between align-items-center">
                <span class="fw-semibold">Net salary</span><span class="h3 mb-0 text-white">{{ money($payroll->net_salary) }}</span>
            </div>
            @if ($payroll->notes)<p class="small text-muted mt-3 mb-0"><i class="bi bi-sticky"></i> {{ $payroll->notes }}</p>@endif
        </x-card>
    </div>
    <div class="col-xl-4">
        <x-card title="Record" icon="bi-info-circle">
            <dl class="op-dl">
                <dt>Salary month</dt><dd>{{ $payroll->period_label }}</dd>
                <dt>Generated by</dt><dd>{{ $payroll->generator?->name ?? '—' }}</dd>
                <dt>Generated</dt><dd>{{ $payroll->created_at->format('M d, Y') }}</dd>
                <dt>Approved by</dt><dd>{{ $payroll->approver?->name ?? '—' }}</dd>
                <dt>Approved</dt><dd>{{ $payroll->approved_at?->format('M d, Y') ?? '—' }}</dd>
            </dl>
        </x-card>
    </div>
</div>

@can('markPaid', $payroll)
    <x-modal id="pay-modal" title="Mark salary as paid" icon="bi-wallet2">
        <form method="POST" action="{{ route('payroll.pay', $payroll) }}">
            @csrf
            <div class="modal-body">
                <p class="text-muted small">Net amount <strong>{{ money($payroll->net_salary) }}</strong> to {{ $payroll->employee->full_name }}.</p>
                <x-form.select name="payment_method" label="Payment method" :options="['bank_transfer' => 'Bank transfer', 'cash' => 'Cash', 'cheque' => 'Cheque', 'other' => 'Other']" value="bank_transfer" required />
            </div>
            <div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Confirm payment</button></div>
        </form>
    </x-modal>
@endcan
@endsection
